class paths:
    dataset = "dataset/"
    raw = dataset + "raw/"
    position_separated = dataset + "position-separated/"
    rookies_removed = dataset + "rookies-removed/"
    concatenated = dataset + "concatenated/"
    images = "images/"
    results = "results/"
    centermen_results = results + "centermen/"
    defensemen_results = results + "defensemen/"
    winger_results = results + "wingers/"
    dv_iv_scatter = "dv_iv_scatter/"
    dv_dv_scatter = "dv_dv_scatter/"